### ISSUE TITLE
AssertionError: The specified fps is higher than the raw video

### ISSUE THREAD

**Issue by imneonizer** [bolianchen/pytorch_depth_from_videos_in_the_wild#5]
The trained kitti model provided in the repository only supports `416x128` resolution I guess because when I tried it on `1920x1080` frame this is the result:
![0000000001](https://user-images.githubusercontent.com/13932346/155730701-6e5e0f45-ca0f-4a4b-bba1-734a151c2030.png)

As you can see some part of the image is not processed.
So I decided to train a model using videos with another resolution `640x480`.

However there is some issue in data generation:
````
Downloading: "https://download.pytorch.org/models/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth" to /root/.cache/torch/hub/checkpoints/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth
100%|█████████████████████████████████████████| 170M/170M [07:36<00:00, 390kB/s]
Traceback (most recent call last):
  File "gen_data.py", line 217, in <module>
    _generate_data()
  File "gen_data.py", line 46, in _generate_data
    dataloader = Video(
  File "/media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/datasets/data_prep/video_loader.py", line 79, in __init__
    self.vid2img()
  File "/media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/datasets/data_prep/video_loader.py", line 127, in vid2img
    assert raw_fps >= fps, "The specified fps is higher than the raw video"
AssertionError: The specified fps is higher than the raw video
````

I check using `ffmpeg` it reports `30.32` FPS of the video (I was trying to generate dataset using single video)

Is it possible to infer the entire Image ? I tried resizing my images to `416x128` resolution but there seems to be false predictions:
![0000000001](https://user-images.githubusercontent.com/13932346/155731381-7cb594e6-caeb-45a4-94fb-8ce9427f7e7f.png)

Please suggest the number of videos and video length for a good-performing model.

**Comment by bolianchen** [comment]
(1)You may use the KITTI pretrained model to predict depth for the lower part of the image by the following command.
python infer_depth.py --input_path path/to/a/folder/containing/images    # or path/to/a/video
                                      --model_path path/to/a/folder/containing/checkpoints
                                      --crop 0 0 0.45 0

(2) Probably opencv couldn't read the fps successfully. Please use the code below to check if a valid value is printed.

vidcap = cv2.VideoCapture(path_to_video)
vidcap.set(cv2.CAP_PROP_POS_MSEC, self.video_start)
raw_fps = vidcap.get(cv2.CAP_PROP_FPS)
print(raw_fps)

If not, you may revise the line#124 in datasets/data_prep/video_loader.py as
raw_fps = 30.32

We may consider to add an option to allow users to manually define raw_fps if it help your situation. Otherwise, we need to figure out an alternative way to correctly retrieve fps from your videos.

For fps=10, number of images to the order of 10^4 should work. Since this method is an SfM-based method, your videos should not be compressed too much to have severe quality loss. Otherwise,  depth maps are likely to have weird artifacts.

**Comment by bolianchen** [comment]
@imneonizer
I may implement one or a combination of the two solutions below:
1. ignore the videos that OpenCV retrieved 0 fps and convert the other videos as normal.
2. add an additional option to let users manually assign fps for the videos with 0 fps retrieved.

Appreciate feedback from you! Thank you!
